### ISSUE TITLE
get() not working correctly inside @each

### ISSUE THREAD

**Issue by connorjburton** [lunelson/sass-list-maps#12]
Hi,

What is your stance on supports grunt-sass? I have an example that isn't working in correctly in grunt-sass.

http://sassmeister.com/gist/facf0dbfe83e3fb4347b

That is the code example, it works fine in Libsass but not grunt-sass.

Thanks,
Connor

**Comment by lunelson** [comment]
Hi, your code example is mixing approaches: sass-list-maps was meant for versions of libsass before the current 3.1 beta, when maps were not yet completely supported. You are using the sass-list-maps syntax, but you're using multi-assignment e.g. `@each $key, $value in $map`, which doesn't work with list-maps or isn't really supported anyway. I suggest you switch to native maps syntax if you are using libsass 3.1b or greater. I have a new version of these functions called [Sass Maps Plus](https://github.com/lunelson/sass-maps-plus), which uses the same functions names e.g. `map-get-z()` but uses the native maps. 

Regarding grunt-sass, I'm not sure what the problem would be, as it uses node-sass, which uses libsass; but it's taking time for those tools to be updated. If you install the node-sass beta before you install grunt-sass it should use the 3.1 beta of libsass. I suggest you post an issue at grunt-sass if this doesn't work

**Comment by connorjburton** [comment]
Okay, thanks for replying, will look into it.

**Comment by connorjburton** [comment]
Just to leave more information if anyone sees this that has the same problem, Sass Maps Plus solved the problem whilst still using native map syntax.
