### ISSUE TITLE
map-get-z not returning nested value

### ISSUE THREAD

**Issue by blackfalcon** [lunelson/sass-list-maps#15]
In a recent experimentation with map-get-z in SassMeister using libsass 3.2.5, it appears that `map-get-z` is not returning the value of the requested list object, but simply the list items as if I only requested the list variable. For example:

```
$layout-containers:
    root (
        default 14,
        form 6
    ),
    desktop (
        default 14,
        form 6
    ),
    desktop-large (
        default 16,
        form 6
    );
```

And then 

```
block {
  width: map-get-z($layout-containers, root, form);
}
```

should return; 

```
block {
  width: 6;
}
```

but I am getting: 

```
block {
  width: root default 14, form 6, desktop default 14, form 6, desktop-large default 16, form 6;
}
```

**Comment by lunelson** [comment]
I'm not sure what could be going on there Dale, it works for me here http://sassmeister.com/gist/6d40effbadae0a366854.

... but may I ask: is there a reason you're still using this library and not moving to native maps? I'm sure you'll experience greater reliability with native maps, as the list polyfill has a few edge cases. The equivalent functions for `map-get-z` etc. in native maps are at https://github.com/lunelson/sass-maps-plus
